language: java
before_install:
  - export TZ=America/New_York
install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PATH="$HOME/sejda-console-3.2.81/bin:$PATH"

  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda update --all;
      conda install tectonic;
    fi
  - if ! command -v sejda-console > /dev/null; then
      wget https://github.com/torakiki/sejda/releases/download/v3.2.81/sejda-console-3.2.81-bin.zip;
      unzip sejda-console-3.2.81-bin.zip;
      mv sejda-console-3.2.81 $HOME/;
    fi
  - conda info -a
  - find $HOME/sejda*;
  - echo $PATH;
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache
    - $HOME/sejda-console-3.2.81
script:
 - mkdir -p result
 - tectonic ./dissertation.tex --print -o result -r 2
 - bash -e split.sh
 - ls chapters > result/chapters.txt
 - mv chapters result/
 - cp index.html result/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: result
  verbose: true
  on:
    branch: master
